### ISSUE TITLE
Package checklist

### ISSUE THREAD

**Issue by Lextuga007** [nhs-r-community/NHSRepisodes#13]
We are building a [style guide](https://github.com/The-Strategy-Unit/data_science/tree/add_style_guide) in the data science team at the Strategy Unit and some of the points would be useful in packages in the NHS-R community repositories too:

- [ ] {styler} - to ensure tidyverse style is used throughout the package
- [ ] {linter} - useful for ensuring things like 80 character lengths for code and consistencies in naming conventions
- [ ] use versioning for package `usethis::use_version()` is helpful for getting the documentation updated
- [ ] use a NEW.md to track the changes between versions `usethis::use_news_md()`
- [ ] linter picks up the use of `code -> name` rather than `name <- code`
